apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: acceleration-app-rwf
spec:
  components:
    - name: acceleration-rwf
      type: edgefarm-applications
      properties:
        image: ghcr.io/ci4rail/edgefarm-accel-demo-edgeapp/accel-samples-railwayforum:1.2.0
        nodepoolSelector:
          matchLabels:
            accel-demo-rwf: ""
        name: acceleration-rwf
        cpu: 0.25
        memory: 256Mi
      traits:
        - type: edgefarm-network
          properties:
            network:
              name: acceleration-network
              subnetwork: edge-to-cloud
              user: publish
        
