apiVersion: v1
kind: Node
metadata:
  labels:
    kubernetes.io/hostname: ac100a
    openyurt.io/is-edge-worker: "true"
    apps.openyurt.io/desired-nodepool: ac100a
    kubernetes.io/arch: arm64
    kubernetes.io/os: linux
  annotations:
    apps.openyurt.io/binding: "true"
  name: ac100a
spec:
  taints:
    - effect: NoSchedule
      key: edgefarm.io
---
apiVersion: apps.openyurt.io/v1beta1
kind: NodePool
metadata:
  name: ac100a
  labels:
    ac100a: ""
    monitor.edgefarm.io/metrics: default
    accel-demo-edge: ""
spec:
  selector:
    matchLabels:
      apps.openyurt.io/nodepool: ac100a
  type: Edge
