apiVersion: v1
kind: Node
metadata:
  labels:
    # todo: kubernetes.io/arch: arm64 amd64 
    kubernetes.io/os: linux
    kubernetes.io/hostname: lizard
    openyurt.io/is-edge-worker: "true"
    apps.openyurt.io/desired-nodepool: lizard
  annotations:
    apps.openyurt.io/binding: "true"
  name: lizard
spec:
  taints:
    - effect: NoSchedule
      key: edgefarm.io
---
apiVersion: apps.openyurt.io/v1beta1
kind: NodePool
metadata:
  name: lizard
  labels:
    lizard: ""
    monitor.edgefarm.io/metrics: default
    accel-demo-edge-xx: ""
spec:
  selector:
    matchLabels:
      apps.openyurt.io/nodepool: lizard
  type: Edge
