apiVersion: v1
kind: Node
metadata:
  labels:
    # todo: kubernetes.io/arch: arm64 amd64 
    kubernetes.io/os: linux
    kubernetes.io/hostname: gecko-right
    openyurt.io/is-edge-worker: "true"
    apps.openyurt.io/desired-nodepool: gecko-right
  annotations:
    apps.openyurt.io/binding: "true"
  name: gecko-right
spec:
  taints:
    - effect: NoSchedule
      key: edgefarm.io
---
apiVersion: apps.openyurt.io/v1beta1
kind: NodePool
metadata:
  name: gecko-right
  labels:
    gecko-right: ""
    monitor.edgefarm.io/metrics: default
spec:
  selector:
    matchLabels:
      apps.openyurt.io/nodepool: gecko-right
  type: Edge
